"""feat: models

Revision ID: b95b898a77cf
Revises: 
Create Date: 2025-05-31 18:34:35.899362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b95b898a77cf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('permissoes', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usuarios')),
    schema='identity'
    )
    op.create_index(op.f('ix_identity_usuarios_email'), 'usuarios', ['email'], unique=True, schema='identity')
    op.create_table('produtos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.String(length=1000), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=False),
    sa.Column('unidade_medida', sa.String(length=10), nullable=False),
    sa.Column('nivel_minimo', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_produtos')),
    schema='inventory'
    )
    op.create_index(op.f('ix_inventory_produtos_ativo'), 'produtos', ['ativo'], unique=False, schema='inventory')
    op.create_index(op.f('ix_inventory_produtos_categoria'), 'produtos', ['categoria'], unique=False, schema='inventory')
    op.create_index(op.f('ix_inventory_produtos_sku'), 'produtos', ['sku'], unique=True, schema='inventory')
    op.create_table('estoque_produtos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('produto_id', sa.UUID(), nullable=False),
    sa.Column('quantidade_atual', sa.Integer(), nullable=False),
    sa.Column('quantidade_reservada', sa.Integer(), nullable=False),
    sa.Column('nivel_minimo', sa.Integer(), nullable=False),
    sa.Column('unidade_medida', sa.String(length=10), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['inventory.produtos.id'], name=op.f('fk_estoque_produtos_produto_id_produtos')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_estoque_produtos')),
    schema='inventory'
    )
    op.create_index(op.f('ix_inventory_estoque_produtos_produto_id'), 'estoque_produtos', ['produto_id'], unique=True, schema='inventory')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_estoque_produtos_produto_id'), table_name='estoque_produtos', schema='inventory')
    op.drop_table('estoque_produtos', schema='inventory')
    op.drop_index(op.f('ix_inventory_produtos_sku'), table_name='produtos', schema='inventory')
    op.drop_index(op.f('ix_inventory_produtos_categoria'), table_name='produtos', schema='inventory')
    op.drop_index(op.f('ix_inventory_produtos_ativo'), table_name='produtos', schema='inventory')
    op.drop_table('produtos', schema='inventory')
    op.drop_index(op.f('ix_identity_usuarios_email'), table_name='usuarios', schema='identity')
    op.drop_table('usuarios', schema='identity')
    # ### end Alembic commands ###
